/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingIndexRouteImport } from './routes/writing/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WritingSlugRouteImport } from './routes/writing/$slug'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminPostsNewRouteImport } from './routes/admin/posts.new'
import { Route as AdminPostsSlugEditRouteImport } from './routes/admin/posts.$slug.edit'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingIndexRoute = WritingIndexRouteImport.update({
  id: '/writing/',
  path: '/writing/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/writing/$slug',
  path: '/writing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsNewRoute = AdminPostsNewRouteImport.update({
  id: '/admin/posts/new',
  path: '/admin/posts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsSlugEditRoute = AdminPostsSlugEditRouteImport.update({
  id: '/admin/posts/$slug/edit',
  path: '/admin/posts/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/login': typeof AdminLoginRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/writing/': typeof WritingIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/posts/$slug/edit': typeof AdminPostsSlugEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/login': typeof AdminLoginRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/admin': typeof AdminIndexRoute
  '/writing': typeof WritingIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/posts/$slug/edit': typeof AdminPostsSlugEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/login': typeof AdminLoginRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/writing/': typeof WritingIndexRoute
  '/admin/posts/new': typeof AdminPostsNewRoute
  '/admin/posts/$slug/edit': typeof AdminPostsSlugEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin/login'
    | '/writing/$slug'
    | '/admin/'
    | '/writing/'
    | '/admin/posts/new'
    | '/admin/posts/$slug/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin/login'
    | '/writing/$slug'
    | '/admin'
    | '/writing'
    | '/admin/posts/new'
    | '/admin/posts/$slug/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin/login'
    | '/writing/$slug'
    | '/admin/'
    | '/writing/'
    | '/admin/posts/new'
    | '/admin/posts/$slug/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminLoginRoute: typeof AdminLoginRoute
  WritingSlugRoute: typeof WritingSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  WritingIndexRoute: typeof WritingIndexRoute
  AdminPostsNewRoute: typeof AdminPostsNewRoute
  AdminPostsSlugEditRoute: typeof AdminPostsSlugEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/': {
      id: '/writing/'
      path: '/writing'
      fullPath: '/writing/'
      preLoaderRoute: typeof WritingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/writing/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/new': {
      id: '/admin/posts/new'
      path: '/admin/posts/new'
      fullPath: '/admin/posts/new'
      preLoaderRoute: typeof AdminPostsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/$slug/edit': {
      id: '/admin/posts/$slug/edit'
      path: '/admin/posts/$slug/edit'
      fullPath: '/admin/posts/$slug/edit'
      preLoaderRoute: typeof AdminPostsSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminLoginRoute: AdminLoginRoute,
  WritingSlugRoute: WritingSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  WritingIndexRoute: WritingIndexRoute,
  AdminPostsNewRoute: AdminPostsNewRoute,
  AdminPostsSlugEditRoute: AdminPostsSlugEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
